//
//  SearchMusicPresenter.swift
//  ItunesSearcher
//
//  Created by Михаил Звягинцев on 25.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchMusicPresentationLogic {

    func presentAlbums(response: SearchMusic.SearchAlbums.Response)
    func presentAlert(error: Error)
    func stopActivityIndicator()
}

class SearchMusicPresenter: SearchMusicPresentationLogic {

    weak var viewController: SearchMusicDisplayLogic?

    func presentAlert(error: Error) {
        viewController?.displayAlert(with: error.localizedDescription)
    }
    func stopActivityIndicator() {
        viewController?.searchFromHistory()
    }
    func presentAlbums(response: SearchMusic.SearchAlbums.Response) {
        var viewModel = SearchMusic.SearchAlbums.ViewModel(albumsData: [])
        for item in response.albumsData {
            let title = item.collectionName?.capitalized ?? "No title"
            let imageURL = item.artworkUrl100 ?? ""
            let albumID = item.collectionId ?? 0
            var autor = ""
            if let _ = item.artistName {
                autor = item.artistName! + " - "
            }
            viewModel.albumsData.append(SearchMusic.SearchAlbums.ViewModel.AlbumData(
                title: title,
                imageURL: imageURL,
                albumID: albumID,
                artist: autor
            ))
        }
        viewController?.displaySearchAlbumsResult(viewModel: viewModel)
    }
}
