//
//  SearchMusicModels.swift
//  ItunesSearcher
//
//  Created by Михаил Звягинцев on 25.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchMusic {

    enum SearchAlbums {
        struct Request {
            let searchText: String
        }
        struct Response {
            let albumsData: [SearchAlbumResult]
        }
        struct ViewModel {
        var albumsData: [AlbumData]
            struct AlbumData {
                let title: String
                let imageURL: String
                let albumID: Int
                let artist: String
            }
        }
    }
}
