//
//  SearchMusicRouter.swift
//  ItunesSearcher
//
//  Created by Михаил Звягинцев on 25.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchMusicDataPassing {
    
    var dataStore: SearchMusicDataStore? { get }
    func showAlbumDetailsViewController(at index: Int)
}

class SearchMusicRouter: SearchMusicDataPassing {

    weak var viewController: SearchMusicViewController?
    var dataStore: SearchMusicDataStore?

    func showAlbumDetailsViewController(at index: Int) {
        let detailsVC = AlbumDetailsViewController()
        detailsVC.albumID = dataStore?.albumIDs[index]
        viewController?.navigationController?.pushViewController(detailsVC, animated: true)
    }
}
