//
//  AlbumDetailsModels.swift
//  ItunesSearcher
//
//  Created by Михаил Звягинцев on 26.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AlbumDetails {

  enum ShowAlbumDetails {
      
    struct Request {
        let albumID: Int
    }
    struct Response {
        let albumDetails: SearchAlbumDetailsModel
    }
    struct ViewModel {
        let imageURL: String
        let albumTitle: String
        let artist: String
        let details: String
        let songs: [String]
    }
  }
}
