//
//  AlbumDetailsInteractor.swift
//  ItunesSearcher
//
//  Created by Михаил Звягинцев on 26.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumDetailsBusinessLogic {

    func showAlbumDetails(request: AlbumDetails.ShowAlbumDetails.Request)
    func showAlbumImage(imageURL: String)
}

class AlbumDetailsInteractor: AlbumDetailsBusinessLogic {

    var presenter: AlbumDetailsPresentationLogic?

    func showAlbumImage(imageURL: String) {
        guard let url = URL(string: imageURL) else {
            presenter?.presentDefaultImage()
            return
        }
        ImageDataLoader.shared.loadImage(url: url) { result in
            do {
                let data = try result.get()
                self.presenter?.presentImage(imageData: data)
            } catch {
                self.presenter?.presentDefaultImage()
            }
        }
    }

    func showAlbumDetails(request: AlbumDetails.ShowAlbumDetails.Request) {
        guard let url = URLBuilder().buildAlbumDetailsSearch(albumID: request.albumID) else {
            presenter?.presentAlert(error: CustomErrors.wrongData)
            return
        }
        NetworkManager.shared.fetchData(from: url, resultType: SearchAlbumDetailsModel.self) { result in
            do {
                let albumData = try result.get()
                if albumData.results.isEmpty {
                    self.presenter?.presentAlert(error: CustomErrors.wrongData)
                    return
                }
                let response = AlbumDetails.ShowAlbumDetails.Response(albumDetails: albumData)
                self.presenter?.presentAlbumDetails(response: response)
            } catch {
                self.presenter?.presentAlert(error: error)
            }
        }
    }
}
