//
//  AlbumInfoInteractor.swift
//  ItunesSearcher
//
//  Created by Михаил Звягинцев on 25.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumInfoBusinessLogic {

    func showAlbumImage(request: AlbumInfo.ShowAlbumCellCell.Request)
}


class AlbumInfoInteractor: AlbumInfoBusinessLogic {

    var presenter: AlbumInfoPresentationLogic?

    func showAlbumImage(request: AlbumInfo.ShowAlbumCellCell.Request) {

        if let url = URL(string: request.imageUrl) {
            ImageDataLoader.shared.loadImage(url: url) {result in
                do {
                    let imageData = try result.get()
                    let response = AlbumInfo.ShowAlbumCellCell.Response(imageData: imageData)
                    self.presenter?.presentAlbumImage(response: response)
                } catch {
                    self.presenter?.presentDefaultImage()
                }
            }
        }
    }
}
